//CREATE VARIABLES WITH FUNCTIONS
//Validate string names when i create a room
const validateName = str => { //CON .trim() ME PERMITIRA QUITAR DEL STRING LO QUE DESEO EN ESTA CASO ME QUITE LO ESPACIOS VACIOS ANTES Y DESPUES DE UNA FRASE O PALABRA EN CASO ME EQUIVOQUE
    return typeof str === 'string' && str.trim().length > 0; //TIENE QUE SER MAYOR A CERO YA QUE EN CASO ALGUIEN SOLO PONGA PURO ESPACIO EN BLANCO DIRE QUE EL NOMBRE NO CUMPLE CON EL ESTADAR PAR QUE ASI SE LLAMA EL CHAT
};

//EXPORTING VARIABLE OR CONSTANT WITH THE FUNCTION
module.exports = { validateName };